version: "1"

services:
  client:
    build: .
    command: sh -c "npm install && npm start"
    working_dir: /root/client
    ports:
      - 8080:8080
    volumes:
      - ./client:/root/client:cached
    depends_on:
      - api

  server:
    build: .
    command: sh -c "npm install && npm start"
    working_dir: /root/server
    ports:
      - 3000:3000
    volumes:
      - ./server:/root/server:cached
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - budget-postgress-data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=password

volumes: 
  budget-postgress-data: